---
- name: install python3 and pip
  yum:
    name:
    - python3
    - python3-pip
    state: latest

- name: install required pip modules if pip3 is installed
  pip:
    name: 
    - mcrpc
    - requests
    executable: pip3
  failed_when: no

- name: install required pip modules if pip3 is installed
  pip:
    name:
    - mcrpc
    - requests
  failed_when: no
