---
- name: create ansible user for deployment
  hosts: roottotal
  become: no
  roles:
  - user-add

- name: prepare hosts for deployment
  hosts: total
  become: yes
  roles:
  - yum-update
  - hostname-set
  - time-set

- name: install multichain
  hosts: total
  become: yes
  roles:
  - multichain-install

- name: deploy multichain
  hosts: serviceProvider
  become: no
  roles:
  - multichain-deploy 

- name: attach the other servers to multichain
  hosts: partners
  become: no
  roles:
  - multichain-attach

- name: create getting started material
  hosts: all
  become: yes
  roles:
  - multichain-getting-started
