---
- name: start blockchain named {{ blockchainName }} on startup
  cron: 
    name: "blockchain {{ blockchainName }}"
    state: present
    special_time: reboot
    job: "sleep 5 && /usr/local/bin/multichaind {{ blockchainName }} -explorersupport=2 -rpcallowip=0.0.0.0/0 > /home/ansible/multichain.log"
    user: ansible
  register: cronResultBlockchain

- name: start explorer for {{ blockchainName }} on startup
  cron:
    name: "explorer {{ blockchainName }}"
    state: present
    special_time: reboot
    job: "sleep 10 && cd /home/ansible/multichain-explorer-2 && python3 -m explorer config.ini > /home/ansible/explorer.log"
    user: ansible
  register: cronResultExplorer
