---
- name: create blockchain named {{ blockchainName }}
  command: "/usr/local/bin/multichain-util create {{ blockchainName }}"
  args:
    creates: "/home/ansible/.multichain/{{ blockchainName }}/params.dat"
  register: deployResult

- name: specify parameters in params.dat file for default port setting to {{ networkPort }} for network port and {{ rpcPort }} for rpcport
  lineinfile:
    path: "/home/ansible/.multichain/{{ blockchainName }}/params.dat"
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
  loop:
    - regexp: "default-rpc-port"
      line: "default-rpc-port = {{ rpcPort }}"
    - regexp: "default-network-port"
      line: "default-network-port = {{ networkPort }}"

- name: start blockchain named {{ blockchainName }} on startup
  cron: 
    name: "blockchain {{ blockchainName }}"
    state: present
    special_time: reboot
    job: "sleep 5 && /usr/local/bin/multichaind {{ blockchainName }} -daemon >> /home/ansible/.multichain/{{ blockchainName }}/autostart.log"
    user: ansible
  register: cronResult

- name: reboot when cron changed
  reboot:
  become: yes
  when: cronResult.changed or deployResult.changed

- name: wait 10 seconds for cronjob to run successfully
  pause:
    seconds: 10
  when: cronResult.changed or deployResult.changed
