---
- name: reboot when cron changed
  reboot:
  become: yes
  when: |
    cronResultBlockchain.changed or
    cronResultExplorer.changed or
    deployResult.changed

- name: wait 10 seconds for cronjob to run successfully
  pause:
    seconds: 10
  when: cronResultBlockchain.changed or cronResultExplorer.changed or deployResult.changed
