---
- name: reboot when cron changed
  reboot:
  become: yes
  when: cronResult.changed or deployResult.changed

- name: wait 10 seconds for cronjob to run successfully
  pause:
    seconds: 10
  when: cronResult.changed or deployResult.changed
