---
- name: download multichain
  unarchive:
    src: https://www.multichain.com/download/multichain-2.1.2.tar.gz
    dest: /
    remote_src: yes

- name: install multichain
  file:
    src: "/multichain-2.1.2/{{ item }}"
    dest: "/usr/local/bin/{{ item }}"
    state: link
  loop:
  - multichaind
  - multichain-cli
  - multichain-util
