---
- name: Add the OS specific varibles
  include_vars: "{{ ansible_os_family }}.yml"

- name: Create the network configuration file for ethernet interfaces
  template:
    src: "ethernet_{{ ansible_os_family }}.j2"
    dest: "{{ net_path }}/ifcfg-{{ item.device }}"
  loop: "{{ network_ether_interfaces }}"
  when: 
    - network_ether_interfaces is defined
    - network_bond_interfaces is not defined
  notify: reboot
