---
- name: Check if reboot is required
  stat:
    path: /var/run/reboot-required
  register: reboot_required_file

- name: reboot machine if reboot is required
  reboot:
  when: reboot_required_file.stat.exists
