---
- name: start firewalld
  service:
    name: firewalld
    state: started
    enabled: yes

- name: open default multichain network port {{ networkPort }} and rpc port {{ rpcPort }}
  firewalld:
    port: "{{ item }}/tcp"
    permanent: yes
    state: enabled
    immediate: yes
  loop:
  - "{{ networkPort }}"
  - "{{ rpcPort }}"
  - "{{ explorerPort }}"
